FROM centos:6.6
MAINTAINER "Luca Gioppo" <gioppo@csi.it>

# ADDING REPOS
RUN rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm \
  && rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.no$
  && yum install -y puppet tar

